version: "3.8"

services:
  node:
    image: node:16
    tty: true
    stdin_open: true
    command: bash
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    container_name: app-investimentos
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOST: db
      JWT_SECRET: "${JWT_SECRET}"

  db:
    container_name: app-investimentos-db
    image: mysql:8.0.21
    restart: unless-stopped
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
networks:
  default:
    name: app-investimentos-net
