on:
  [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn lint

  coverage:
      permissions:
        checks: write
        pull-requests: write
        contents: write
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ArtiomTr/jest-coverage-report-action@v2
