on:
  [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint
